[package]

name = "content_type"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
version = "0.1.0"
build = "./generate"

[lib]

name = "content_type"
path = "src/lib.rs"

[dependencies.http]

git = "https://github.com/reem/rust-http.git"
branch = "temp"

